### ISSUE TITLE
3.9.0.28 找不到密钥

### ISSUE THREAD

**Issue by bcdlbgm** [0xlane/wechat-dump-rs#13]

**Comment by 0xlane** [comment]
有啥报错吗，提供一下日志

**Comment by bcdlbgm** [comment]
没事了，只是因为x86的问题。另外有个问题是处于mac下的虚拟机中登录32位的微信3.9.7.28，会找不到account地址，换到win下没有这个问题。因为我没有mac所以具体没办法调试。
