### ISSUE TITLE
win7 用会报错。

### ISSUE THREAD

**Issue by digjack** [0xlane/wechat-dump-rs#16]
win7环境下执行，会报错。
`read file version failed`

**Comment by 0xlane** [comment]
用的什么版本呢，可以看看微信的主进程文件右键属性里是没有文件版本信息的吗

**Comment by anwen-anyi** [comment]
现在还支持 `Windows7` 吗？

**Comment by 0xlane** [comment]
> 现在还支持 `Windows7` 吗？ 我运行提示错误 ![image](https://private-user-images.githubusercontent.com/56105412/386576607-249942dd-fe3e-4487-8ad9-85ca5b777086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzE0MzAsIm5iZiI6MTczMTY3MTEzMCwicGF0aCI6Ii81NjEwNTQxMi8zODY1NzY2MDctMjQ5OTQyZGQtZmUzZS00NDg3LThhZDktODVjYTViNzc3MDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDExNDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZDlhMDkyYzQwMDMyMDk5YzFkN2VmMjA1ZDQxYzczYzBmODdlZmJlODdlNTZiYTM1MTU1MmIwYjg3MDJiN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._NhFRWNqkMO90teCHEXJoWxlvCsD1oatmMtGubObx_0)

win7我没测试过，据 https://github.com/clash-verge-rev/clash-verge-rev/issues/1041#issuecomment-2266641206 说rust不支持win7了，可能运行异常，需要使用win7专用的工具链编译
