### ISSUE TITLE
导出缺少表  ContactLabel  

### ISSUE THREAD

**Issue by digjack** [0xlane/wechat-dump-rs#17]
微信版本 3.9.10.19
dump出来的数据库缺少表 ContactLabel
中间切换过微信，不知道是不是跟切换授权微信有关系。
另外一种情况，是不是没有缓存到 标签数据，本地就不会有表  ContactLabel

**Comment by 0xlane** [comment]
时间较久，比较难排查了，可以用最新版看看，支持了4.0
