### ISSUE TITLE
file is not exsit

### ISSUE THREAD

**Issue by lww0813** [0xlane/wechat-dump-rs#18]
我修改过我的微信路径，目前为G:\WeChat Files
执行wechat-dump-rs.exe报错：G:\WeChat Files\wxid_4bwa1yvxxxxx\Msg\ChatRoomUser.db  G:\WeChat Files\wxid_4bwa1yvxxxxx\Msg\Misc.db is not exsit: Error { kind: InvalidInput, message: "strings passed to WinAPI cannot contain NULs" },我确保文件是存在的，我不清楚为什么会报这样的错误
微信版本：3.9.10.27
Release:V1.0.6

**Comment by 0xlane** [comment]
这个情况应该是取 微信数据目录的 正则捕获到了`G:\WeChat Files\wxid_4bwa1yvxxxxx\Msg\ChatRoomUser.db G:\WeChat Files\wxid_4bwa1yvxxxxx`这个路径当数据根目录，实际应该捕获为 `G:\WeChat Files\wxid_4bwa1yvxxxxx`，我改一下正则就可以

**Comment by 0xlane** [comment]
修复了 -a 没有任何输出的问题
