### ISSUE TITLE
执行出错 

### ISSUE THREAD

**Issue by BigDataNinjia** [0xlane/wechat-dump-rs#2]
C:\secure\wechat-dump-rs-main>wechat-dump-rs.exe
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [211, 239, 200, 184, 46, 101, 120, 101], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', C:\Users\thin0\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tasklist-0.2.12\src\lib.rs:217:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 0xlane** [comment]
看看进程列表里是不是有一些进程名有乱码呢，看着211, 239, 200, 184这四个不是正常的utf8字符导致我用的一个第三方库里报错的。或者直接找到 微信进程的pid，用-p参数也行

**Comment by BigDataNinjia** [comment]
使用 -p 参数后，报错
[+] wechat version is 3.9.7.25
thread 'main' panicked at 'Misc.db is not exsit: Os { code: 3, kind: NotFound, message: "系统找不到指定的路径。" }', src\main.rs:286:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
是我哪里环境出问题了吗？

**Comment by 0xlane** [comment]
你看看微信版本是什么版本呀，需要用到微信数据目录下的misc.db文件做key验证，你看看是不是没这个文件呢

**Comment by raspberryhusky** [comment]
这个库是我写的，当时没处理好非UTF-8的字符集，你用最新的0.2.13就好了
https://github.com/yalishandar/tasklist-rs/pull/3

> 你看看微信版本是什么版本呀，需要用到微信数据目录下的misc.db文件做key验证，你看看是不是没这个文件呢
