### ISSUE TITLE
提取的密钥可以解密前几年保存的聊天记录吗？

### ISSUE THREAD

**Issue by mailfarmer** [0xlane/wechat-dump-rs#20]
手机丢了，电脑上只有在19年登录过，我用您的工具提取的key，去解密电脑上19年的聊天记录时，提示
=====================================================
decryption in progress, please wait...
thread 'main' panicked at src\main.rs:610:77:
called `Result::unwrap()` on an `Err` value: Hash verification failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
=====================================================
是不是微信中间换过密钥的生成方式？还是因为我中间改过id，造成了密钥变化？

**Comment by 0xlane** [comment]
电脑登录微信后可以看到这些19年的聊天记录吗，能看到说明可以解，此时进程中的key和db文件肯定是对应的

**Comment by 0xlane** [comment]
我看你这个报错，应该是从另外一个数据目录对应的微信进程获取的key（因为这个工具找key的原理类似爆破，尝试解成功才会输出key，所以你能拿到key，肯定是可以解成功的）
你这个报错应该是你用这个key去解密其他微信进程产生的数据库文件了，这个key只能解密当前微信进程里配置的目录，拿去解其他的就不行。

你可以试试用同账号登录微信后关闭，然后把你要解密的数据目录（目录内容必须完整）覆盖到当前配置的目录里，再打开微信看看微信能不能读出来。

能读出来的话就不需要用这个工具了，直接和你的新手机微信聊天记录同步一下就行，微信自带的备份功能。

**Comment by mailfarmer** [comment]
事实上是先试的覆盖目录的方法，无效才想着去找类似你这样的工具，想着先从当前的微信读取密钥，然后去解老的聊天记录

**Comment by cnsimo** [comment]
那估计没戏了，密钥不对，微信自己进程都读不出来，找第三方工具就更不可能解出来了

**Comment by 0xlane** [comment]
那估计没戏了，密钥不对，微信自己进程都读不出来，找第三方工具就更不可能解出来了
