### ISSUE TITLE
这个工具要怎么用

### ISSUE THREAD

**Issue by AC051988** [0xlane/wechat-dump-rs#21]
怎样才能运行这个工具呢？

**Comment by 0xlane** [comment]
先登录微信，然后在cmd里执行 .\wechat-dump-rs.exe -a

**Comment by AC051988** [comment]
![Capture](https://github.com/user-attachments/assets/58e3fe87-753f-47c7-a7c2-0637e3273618)
下载的文件夹里没有这个 .exe 程序， 运行不了。 是我少了些什么吗？

**Comment by 0xlane** [comment]
在release里面下载编译好的程序：https://github.com/0xlane/wechat-dump-rs/releases，你下载的应该是源码文件

**Comment by AC051988** [comment]
![Capture](https://github.com/user-attachments/assets/d94e00f6-7e80-4fd0-abc1-8a6409611dc0)
我下载了运行之后没有输出任何结果， 解密完的文档会存到哪里？

**Comment by 0xlane** [comment]
装一下vc++运行环境：https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-140

**Comment by 0xlane** [comment]
你有什么需求可以说一下，感觉你不适合用这个呢

**Comment by AC051988** [comment]
我想解密微信的聊天记录

**Comment by 0xlane** [comment]
好，不是聊天备份就行，因为只是解数据库文件，没有进一步解析，原始的数据内容，解出来大多时候也就是看看文本记录或者看看数据库表结构。

**Comment by AC051988** [comment]
我就是想通过解密pc端的微信数据库文档来找出聊天记录

**Comment by AC051988** [comment]
我安装了 VC++ 然后再运行 wechat-dump-rs.exe 还是没有输出任何结果
![Capture](https://github.com/user-attachments/assets/4782cc51-2b88-461f-a814-db9208da15e7)

**Comment by 0xlane** [comment]
没有登录微信吧，找不到微信进程也不会打印任何东西

**Comment by AC051988** [comment]
微信登录了

**Comment by 0xlane** [comment]
为啥不直接在微信里搜索呀，微信搜索不到，这个解出来也不会有

**Comment by 0xlane** [comment]
你看看任务管理器里有这个名字的进程吗：WeChat.exe
找到之后看一下pid
然后用 .\wechat-dump-rs.exe -p <pid>试试，<pid>替换你的微信进程pid

**Comment by 0xlane** [comment]
另外管理员权限运行cmd

**Comment by AC051988** [comment]
我用-p 替换了进程，出了你教程里的那个画面，但是我要去哪里找解密后的数据库文件呢
________________________________

**Comment by AC051988** [comment]
我不是要搜索我的微信，我是要搜索女朋友的微信记录，我发现她有别的男人，我想证实一下
________________________________

**Comment by 0xlane** [comment]
出来了，就加上 -a 参数，就会dump数据库文件，dump路径会打印到结果里：

```powershell
.\wechat-dump-rs.exe -p <pid> -a
```

> 我用-p 替换了进程，出了你教程里的那个画面，但是我要去哪里找解密后的数据库文件呢

**Comment by 0xlane** [comment]
这个工具解密聊天记录需要满足有个条件：**电脑上登录了目标用户的微信**

所以只能dump你现在登录的聊天记录，dump她的就需要到她电脑上登录她的微信然后copy出来，不过提醒你还是在合理范围使用

> 我不是要搜索我的微信，我是要搜索女朋友的微信记录，我发现她有别的男人，我想证实一下
