### ISSUE TITLE
4.0失效

### ISSUE THREAD

**Issue by DMOMAD** [0xlane/wechat-dump-rs#23]

**Comment by DMOMAD** [comment]
4.0的变化非常非常大，进程名、结构、数据库、密钥、暴力搜索手机类型都将不同

**Comment by 0xlane** [comment]
稍微调研了一下，加密算法也变了，后面有时间更新一个版本支持下

**Comment by 0xlane** [comment]
可以下载1.0.10版本试一下，我这里测试版本为4.0.0.26
