### ISSUE TITLE
4.0.0.32 unable to find phone string

### ISSUE THREAD

**Issue by Vxer-Lee** [0xlane/wechat-dump-rs#24]
![image](https://github.com/user-attachments/assets/ff446452-37cf-4f3b-9442-3cb59f61c014)
在朋友电脑上用朋友账号测试了，也都是这个错误。

**Comment by 0xlane** [comment]
绑定了国内手机号吗

**Comment by 0xlane** [comment]
方便的话，用CE在内存里搜一下这个微信绑定的手机号，正常应该能搜到一个，可以把前后的字节内容截个图看下。可能是和我这里不太一样

**Comment by Vxer-Lee** [comment]
> 绑定了国内手机号吗

绑定了国内手机号的

**Comment by 0xlane** [comment]
我知道原因了，哈哈

**Comment by Vxer-Lee** [comment]
> 我知道原因了，哈哈

nb nb

**Comment by 0xlane** [comment]
我写代码的时候昵称长度随便写的是在0x4-0x30之间，手机号、昵称、微信号是连在一起找的，你这儿长度是0x3，所以没匹配到，我待会改一版

**Comment by Vxer-Lee** [comment]
可是密钥好像不太对啊，
![image](https://github.com/user-attachments/assets/1c0eb9c5-1316-4637-86fd-8cceee347ec4)
![image](https://github.com/user-attachments/assets/20821359-b7fe-4d02-8ff6-33fa56c75e77)

**Comment by Vxer-Lee** [comment]
可是密钥好像不太对啊，应该是个不可见的十六进制
![image](https://github.com/user-attachments/assets/754e8a2c-c232-40e6-aab2-88fd989fe462)
![A7844CE4-9A31-4031-806E-EC8AD22D66A4](https://github.com/user-attachments/assets/151e263b-7bfd-4cf8-a861-1d45380e4d82)

**Comment by 0xlane** [comment]
> 可是密钥好像不太对啊，应该是个不可见的十六进制 ![image](https://private-user-images.githubusercontent.com/27657137/386115432-754e8a2c-c232-40e6-aab2-88fd989fe462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzUwMDIsIm5iZiI6MTczMTU3NDcwMiwicGF0aCI6Ii8yNzY1NzEzNy8zODYxMTU0MzItNzU0ZThhMmMtYzIzMi00MGU2LWFhYjItODhmZDk4OWZlNDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4NTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyN2M1NmUxZjlkYWVjOGM3OTQyMzgzM2EwMzMyNTNkYTM3NzM2Njg0ZmQyMzI3N2I2MDAxNThkY2Q5NDc3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XKixyCcX00A0mnd1EUZtQvMQZcnHILUtSOke_tKGA40) ![A7844CE4-9A31-4031-806E-EC8AD22D66A4](https://private-user-images.githubusercontent.com/27657137/386115518-151e263b-7bfd-4cf8-a861-1d45380e4d82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzUwMDIsIm5iZiI6MTczMTU3NDcwMiwicGF0aCI6Ii8yNzY1NzEzNy8zODYxMTU1MTgtMTUxZTI2M2ItN2JmZC00Y2Y4LWE4NjEtMWQ0NTM4MGU0ZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4NTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MTk1NmEyM2U0YmFiYTA2ZGU3NTdlMWQxMWMwNTQ3MjA0NWRhNDM2ZjYzMGE3NDY0NWQ0MjQ1YTNlM2Q3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qKUfuQPfd9GwGVHqfXtAJoSLO-IVPrg3rOJNUyjTyBA)

这个不是密钥，只是个md5，密钥需要暴破出来

我更新了，等action自动把release编译出来后，你再试试ok不ok

**Comment by Vxer-Lee** [comment]
![image](https://github.com/user-attachments/assets/bb566081-a1be-48e1-8845-516909d8281b)
作者nb哈哈哈哈哈，修复是真快啊。
另外作者：） 图片 解密和附件关联有逆过吗

**Comment by 0xlane** [comment]
没，只看了数据库文件，图片之前好像是简单的异或，我记得有个方法也是暴破出来的，图片头是固定内容，只需要0x00-0xff都挨个试一遍就出来了，不知道新版本变了没，你可以再搜搜这块试试，我再有时间可以再想办法在工具里支持解密图片。附件应该是没加密，不需要解。

**Comment by Vxer-Lee** [comment]
> 没，只看了数据库文件，图片之前好像是简单的异或，我记得有个方法也是暴破出来的，图片头是固定内容，只需要0x00-0xff都挨个试一遍就出来了，不知道新版本变了没，你可以再搜搜这块试试，我再有时间可以再想办法在工具里支持解密图片。附件应该是没加密，不需要解。

okok

**Comment by Vxer-Lee** [comment]
> 没，只看了数据库文件，图片之前好像是简单的异或，我记得有个方法也是暴破出来的，图片头是固定内容，只需要0x00-0xff都挨个试一遍就出来了，不知道新版本变了没，你可以再搜搜这块试试，我再有时间可以再想办法在工具里支持解密图片。附件应该是没加密，不需要解。

感谢哈哈
