### ISSUE TITLE
4.0.0.26无法获取到数据

### ISSUE THREAD

**Issue by loudixiaokai** [0xlane/wechat-dump-rs#25]
大神，为什么我在执行wechat-dump-rs后，却返回如下内容呢？
[+] wechat version is 4.0.0.26
thread 'main' panicked at src/main.rs:527:14:
unbale to find data dir
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
谢谢！！

**Comment by 0xlane** [comment]
这个报错是没有获取到数据目录，可以用CE搜一下内存字符串 xwechat_files\wxid_ ，看看能不能搜到你的微信数据目录

**Comment by 0xlane** [comment]
目录路径格式可能和我这里不一样

**Comment by loudixiaokai** [comment]
因为我的微信号不是以wxid开头的，所以才会出现这个错误，我换了个wxid开头的微信号后就没问题了，不过可以修复这个必需以wxid开头的BUG吗？

**Comment by 0xlane** [comment]
和微信号没关系，wxid是刚注册微信时系统自动分配的一个id，但是数据目录路径里的是wxid，不随着微信号改变而改变。  应该是其他原因导致的

**Comment by 0xlane** [comment]
你到文档文件夹看看xwechat_files目录里应该是有wxid的

**Comment by loudixiaokai** [comment]
我的文件夹那里就不是wxid开头，最早一批注册的微信，如果当时设置了微信号，那就不是以wxid开头的。

**Comment by 0xlane** [comment]
已支持，可以试下新版本
