### ISSUE TITLE
运行出现错误

### ISSUE THREAD

**Issue by cf48rty0** [0xlane/wechat-dump-rs#26]
thread 'main' panicked at src/main.rs:131:41:
called `Result::unwrap()` on an `Err` value: Failed to convert win32 path to string.

Caused by:
    invalid utf-8 sequence of 1 bytes from index 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 0xlane** [comment]
微信安装的路径有中文吗

**Comment by anwen-anyi** [comment]
我也是这个错误，安装路径没有中文，微信版本`4.0.0.32`

![image](https://github.com/user-attachments/assets/48de1b42-cf23-4816-8b99-c06c084285ed)

**Comment by 0xlane** [comment]
> 我也是这个错误，安装路径没有中文
> 
> * 微信版本`4.0.0.32`
> * wechat-dump-rs版本`v1.0.14`
> 
> ![image](https://private-user-images.githubusercontent.com/56105412/386434842-48de1b42-cf23-4816-8b99-c06c084285ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Mzg2MDEsIm5iZiI6MTczMTYzODMwMSwicGF0aCI6Ii81NjEwNTQxMi8zODY0MzQ4NDItNDhkZTFiNDItY2YyMy00ODE2LThiOTktYzA2YzA4NDI4NWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAyMzgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYjE3Y2JlOTgwNzJmOGY2NDljZmM2YmUwYTA1YzM5ZmM1MzZhOWQ3YTM5ZGNmYmQzMWY2MjY0OGZjNWZkM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4UYdgCry7itzjK1p2Bf1DSa6K-wIJzMWSL8Ua7XUqt8)

我测试了下中文是会报这个错，改了下代码，等release自动构建出来，试一下1.0.15版本呢

**Comment by anwen-anyi** [comment]
> 我测试了下中文是会报这个错，改了下代码，等release自动构建出来，试一下1.0.15版本呢

还是有错误
```bash
[+] wechat version is 4.0.0.32
thread 'main' panicked at src/main.rs:477:10:
unbale to find phone string
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 0xlane** [comment]
> > 我测试了下中文是会报这个错，改了下代码，等release自动构建出来，试一下1.0.15版本呢
> 
> 还是有错误
> 
> ```shell
> [+] wechat version is 4.0.0.32
> thread 'main' panicked at src/main.rs:477:10:
> unbale to find phone string
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

说明刚刚那个错误解决了，这是另外一个问题。可以参考一下 #24，发一下CE截图我看看

**Comment by anwen-anyi** [comment]
> > > 我测试了下中文是会报这个错，改了下代码，等release自动构建出来，试一下1.0.15版本呢
> > 
> > 
> > 还是有错误
> > ```shell
> > [+] wechat version is 4.0.0.32
> > thread 'main' panicked at src/main.rs:477:10:
> > unbale to find phone string
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > ```
> 
> 说明刚刚那个错误解决了，这是另外一个问题。可以参考一下 #24，发一下CE截图我看看

对，就是省的新开一个issue了

CE搜索不到手机号呀（进程也没绑定错应该，看你在看雪发的也是绑定的这个 微信（测试版）进程）
![image](https://github.com/user-attachments/assets/7c16de73-ab8d-4706-9cdd-21c9795e7356)

**Comment by 0xlane** [comment]
> > > > 我测试了下中文是会报这个错，改了下代码，等release自动构建出来，试一下1.0.15版本呢
> > > 
> > > 
> > > 还是有错误
> > > ```shell
> > > [+] wechat version is 4.0.0.32
> > > thread 'main' panicked at src/main.rs:477:10:
> > > unbale to find phone string
> > > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > ```
> > 
> > 
> > 说明刚刚那个错误解决了，这是另外一个问题。可以参考一下 #24，发一下CE截图我看看
> 
> 对，就是省的新开一个issue了
> 
> CE搜索不到手机号呀（进程也没绑定错应该，看你在看雪发的也是绑定的这个 微信（测试版）进程） ![image](https://private-user-images.githubusercontent.com/56105412/386442032-7c16de73-ab8d-4706-9cdd-21c9795e7356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDAyMjcsIm5iZiI6MTczMTYzOTkyNywicGF0aCI6Ii81NjEwNTQxMi8zODY0NDIwMzItN2MxNmRlNzMtYWI4ZC00NzA2LTljZGQtMjFjOTc5NWU3MzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAzMDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMzI3M2MyYTVmZWEwZTdkNjMzNGFhYzExNjJkOTVhNTc5NmFjYTZlYTI5MWI3NzkzYTY0ZjgxNmZhOTRlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DbEcEl2FnUwz_K0o57WWyR8U82yydcDw48WHq-XQ1Vo)

搜错啦，选new scan，value type 选字符串类型，再搜索一下呢

**Comment by anwen-anyi** [comment]
> 搜错啦，选new scan，value type 选字符串类型，再搜索一下呢

是这个吗？b不太会用CE 😹 
![image](https://github.com/user-attachments/assets/aac3341e-b78e-44f1-b859-bb0d8695fcba)

**Comment by 0xlane** [comment]
@anwen-anyi 往上一点，需要看上面5行。另外字节也部分打码一下 能还原

**Comment by anwen-anyi** [comment]
> @anwen-anyi 往上一点，需要看上面5行。另外字节也部分打码一下 能还原

![image](https://github.com/user-attachments/assets/7717e29d-357b-4b34-9b59-57b9d3c5c1f0)

**Comment by 0xlane** [comment]
> > @anwen-anyi 往上一点，需要看上面5行。另外字节也部分打码一下 能还原
> 
> ![image](https://private-user-images.githubusercontent.com/56105412/386445207-7717e29d-357b-4b34-9b59-57b9d3c5c1f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDExMTIsIm5iZiI6MTczMTY0MDgxMiwicGF0aCI6Ii81NjEwNTQxMi8zODY0NDUyMDctNzcxN2UyOWQtMzU3Yi00YjM0LTliNTktNTdiOWQzYzVjMWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAzMjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZTUwOGM1YjQ0MTcyNTUwMWYxZGUyZjQxNzkzMjE1MTZmYTdkYmFiMDMxZThiZWEwNzA1MGU4MGM4YWFiZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N-ZQtYPKrKri4v4GmYBXbw4PKG7O3HqRiCETa0UWvpQ)

ok，晓得了，昵称、手机号连在一起找的，昵称那里的匹配有点问题，我待会改一下

**Comment by anwen-anyi** [comment]
非+86的可以吗？ :joy_cat:     +852香港的
![image](https://github.com/user-attachments/assets/86c32d13-4576-416b-b142-b76fce8c249c)

**Comment by 0xlane** [comment]
> 非+86的可以吗？ 😹 +852香港的 ![image](https://private-user-images.githubusercontent.com/56105412/386446380-86c32d13-4576-416b-b142-b76fce8c249c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDE1MzYsIm5iZiI6MTczMTY0MTIzNiwicGF0aCI6Ii81NjEwNTQxMi8zODY0NDYzODAtODZjMzJkMTMtNDU3Ni00MTZiLWIxNDItYjc2ZmNlOGMyNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAzMjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZmU4ZjgyNzc2NWNmZGNlYjVjMmNkMmRiZGU4NTU2NDBmYTJlNmNiMGUyOGM5NTRhMTY4Mjg3NmUzMzZlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BgWlCANNUClCB1BWmM-MODH6twnjgk0cKxJCgIWuVYc)

也不是不行，不过各个地方手机号长度都不固定，可能会导致内存里搜到别的内容，而且我没有这种号来测试，有问题可能不好解决，你可以尝试改一下代码里内置的手机号匹配规则自己编译一版用用，学一下yara就行，哈哈

**Comment by 0xlane** [comment]
> > 我测试了下中文是会报这个错，改了下代码，等release自动构建出来，试一下1.0.15版本呢
> 
> 还是有错误
> 
> ```shell
> [+] wechat version is 4.0.0.32
> thread 'main' panicked at src/main.rs:477:10:
> unbale to find phone string
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

已更新1.0.16版本，应该可以解决这个错误

**Comment by anwen-anyi** [comment]
> > 非+86的可以吗？ 😹 +852香港的 ![image](https://private-user-images.githubusercontent.com/56105412/386446380-86c32d13-4576-416b-b142-b76fce8c249c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDE1MzYsIm5iZiI6MTczMTY0MTIzNiwicGF0aCI6Ii81NjEwNTQxMi8zODY0NDYzODAtODZjMzJkMTMtNDU3Ni00MTZiLWIxNDItYjc2ZmNlOGMyNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAzMjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZmU4ZjgyNzc2NWNmZGNlYjVjMmNkMmRiZGU4NTU2NDBmYTJlNmNiMGUyOGM5NTRhMTY4Mjg3NmUzMzZlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BgWlCANNUClCB1BWmM-MODH6twnjgk0cKxJCgIWuVYc)
> 
> 也不是不行，不过各个地方手机号长度都不固定，可能会导致内存里搜到别的内容，而且我没有这种号来测试，有问题可能不好解决，你可以尝试改一下代码里内置的手机号匹配规则自己编译一版用用，学一下yara就行，哈哈

这...难搞啊 我只是一个划水的混子 不是程序员 呜呜呜
- 香港的应该长度好像都是8位数的，方便做一下么~

编译好了，去试试v1.0.16

**Comment by anwen-anyi** [comment]
v1.0.16可以正常使用了 么么哒~

**Comment by 0xlane** [comment]
> > > 非+86的可以吗？ 😹 +852香港的 ![image](https://private-user-images.githubusercontent.com/56105412/386446380-86c32d13-4576-416b-b142-b76fce8c249c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDE1MzYsIm5iZiI6MTczMTY0MTIzNiwicGF0aCI6Ii81NjEwNTQxMi8zODY0NDYzODAtODZjMzJkMTMtNDU3Ni00MTZiLWIxNDItYjc2ZmNlOGMyNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAzMjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZmU4ZjgyNzc2NWNmZGNlYjVjMmNkMmRiZGU4NTU2NDBmYTJlNmNiMGUyOGM5NTRhMTY4Mjg3NmUzMzZlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BgWlCANNUClCB1BWmM-MODH6twnjgk0cKxJCgIWuVYc)
> > 
> > 
> > 也不是不行，不过各个地方手机号长度都不固定，可能会导致内存里搜到别的内容，而且我没有这种号来测试，有问题可能不好解决，你可以尝试改一下代码里内置的手机号匹配规则自己编译一版用用，学一下yara就行，哈哈
> 
> 这...难搞啊 我只是一个划水的混子 不是程序员 呜呜呜
> 
> * 香港的应该长度好像都是8位数的加上区号就是11位数（852 1111 2222），方便做一下么~
> 
> 编译好了，去试试v1.0.16

按你说的格式，我教你弄：
1. fork我的仓库到你那里
2. 修改main.rs里的GetPhoneNumberOffset规则，将里面的[0-9]{11}\x00{5}\x0b改成[0-9+]{12}\x00{4}\x0c
3. 打个tag 比如v1.0.16-beta在最新的提交上，等自动构建完成后在release下载就行
如果你说的格式没错的话，应该可以能成功

**Comment by anwen-anyi** [comment]
> > > > 非+86的可以吗？ 😹 +852香港的 ![image](https://private-user-images.githubusercontent.com/56105412/386446380-86c32d13-4576-416b-b142-b76fce8c249c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDE1MzYsIm5iZiI6MTczMTY0MTIzNiwicGF0aCI6Ii81NjEwNTQxMi8zODY0NDYzODAtODZjMzJkMTMtNDU3Ni00MTZiLWIxNDItYjc2ZmNlOGMyNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAzMjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZmU4ZjgyNzc2NWNmZGNlYjVjMmNkMmRiZGU4NTU2NDBmYTJlNmNiMGUyOGM5NTRhMTY4Mjg3NmUzMzZlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BgWlCANNUClCB1BWmM-MODH6twnjgk0cKxJCgIWuVYc)
> > > 
> > > 
> > > 也不是不行，不过各个地方手机号长度都不固定，可能会导致内存里搜到别的内容，而且我没有这种号来测试，有问题可能不好解决，你可以尝试改一下代码里内置的手机号匹配规则自己编译一版用用，学一下yara就行，哈哈
> > 
> > 
> > 这...难搞啊 我只是一个划水的混子 不是程序员 呜呜呜
> > 
> > * 香港的应该长度好像都是8位数的加上区号就是11位数（852 1111 2222），方便做一下么~
> > 
> > 编译好了，去试试v1.0.16
> 
> 按你说的格式，我教你弄：
> 
> 1. fork我的仓库到你那里
> 2. 修改main.rs里的GetPhoneNumberOffset规则，将里面的[0-9]{11}\x00{5}\x0b改成[0-9+]{12}\x00{4}\x0c
> 3. 打个tag 比如v1.0.16-beta在最新的提交上，等自动构建完成后在release下载就行
>    如果你说的格式没错的话，应该可以能成功

反馈一下，按照你的办法，可以使用 😘 
![image](https://github.com/user-attachments/assets/0c68659e-f20a-405f-b67e-7cafce19a66c)

**Comment by lujihong** [comment]
> v1.0.16可以正常使用了 么么哒~

@anwen-anyi 
我用了另一个思路实现，理论上可以支持全球所有国家的手机号，我没有国外手机号，你可以帮我测试一下吗？

[fast-find-key.zip](https://github.com/user-attachments/files/18284646/fast-find-key.zip)
