### ISSUE TITLE
老师可以写一段解密DB文件的VC代码吗？

### ISSUE THREAD

**Issue by loudixiaokai** [0xlane/wechat-dump-rs#27]
老师，谢谢您的分享，执行您的EXE已经完全没有问题，可以把所有DB文件解密为明文数据库。
但老师您还可以写一段执行：wechat-dump-rs.exe -a 后的VC代码吗？也就是写一段解密数据库文件的VC代码。

**Comment by 0xlane** [comment]
没理解您的需求呢，是需要这个工具的c++版本吗

**Comment by loudixiaokai** [comment]
是啊，老师。

**Comment by 0xlane** [comment]
我应该是不会开发c++版本，重写一下工作量太大，需要自己研究一下了

**Comment by johnli1988** [comment]
github 上有开源的 https://github.com/sqlitebrowser/sqlitebrowser.git 
但是这个软件不能直接使用 16进制的数据库秘钥，我改进了一下可以直接使用了

https://github.com/johnli1988/SQLCipherForWeixin
