### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by cf48rty0** [0xlane/wechat-dump-rs#28]
thread 'main' panicked at src/main.rs:131:41:
called `Result::unwrap()` on an `Err` value: Failed to get process name with PID 4: 31

Caused by:
    连到系统上的设备没有发挥作用。 (0x8007001F)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 0xlane** [comment]
看报错好像是遍历系统进程的时候被中断了，再跑一次也这样吗

**Comment by Vxer-Lee** [comment]
> thread 'main' panicked at src/main.rs:131:41: called `Result::unwrap()` on an `Err` value: Failed to get process name with PID 4: 31
> 
> Caused by: 连到系统上的设备没有发挥作用。 (0x8007001F) note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

你这个一般是被调试器，或者frida,CE占用了，你把其他的关了就行。

**Comment by 0xlane** [comment]
我大概知道了，通过管理员运行的时候会出现这个问题，原因在于解析进程列表时被保护的系统进程实际获取不到进程名，1.0.17版本修复
