### ISSUE TITLE
运行报错：thread 'main' panicked at src/main.rs:302:54: read phone type string failed: invalid utf8 string

### ISSUE THREAD

**Issue by zhangshengpu** [0xlane/wechat-dump-rs#31]
大佬，运行后报错：

thread 'main' panicked at src/main.rs:302:54:
read phone type string failed: invalid utf8 string

**Comment by zhangshengpu** [comment]
let phone_type_string =
        read_string(pid, phone_type_string_addr, 20).expect("read phone type string failed");
302行是不是查找手机号，手机号需要20个字符？为什么是20呢？

**Comment by zhangshengpu** [comment]
[+] wechat version is 3.9.12.17

**Comment by 0xlane** [comment]
微信3.x先用109版本，工具新版本更新了些依赖，可能是这个原因，我看看

**Comment by 0xlane** [comment]
> ```
> let phone_type_string =
>     read_string(pid, phone_type_string_addr, 20).expect("read phone type string failed");
> ```
> 
> 302行是不是查找手机号，手机号需要20个字符？为什么是20呢？

这个是找登录手机类型，20是随便写的，转换字符串会到\x00自动终止所以写20也行，实际转换出来的字符串只有android和iphone两个值

**Comment by 0xlane** [comment]
知道原因了，昨天对微信4.0提交的优化代码里 https://github.com/0xlane/wechat-dump-rs/blob/6934f9d104ded555a513964b970941b45db7cbf9/src/main.rs#L193 这个地方限制了参数指定的大小必须和解析出来的大小一致，否则判定读取失败。我修复一下，用之前的版本应该没问题

**Comment by 0xlane** [comment]
已在1019版本修复
