### ISSUE TITLE
4.0登陆微信后运行提示，管理员打开状态

### ISSUE THREAD

**Issue by DMOMAD** [0xlane/wechat-dump-rs#32]
[+] wechat version is 4.0.0.32
thread 'main' panicked at src/main.rs:496:10:
unbale to find phone string
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by DMOMAD** [comment]
> 绑定手机号了吧，参考一下 [#24 (comment)](https://github.com/0xlane/wechat-dump-rs/issues/24#issuecomment-2475661350) ，截个CE手机号内存的图吧

我应该是属于没有绑定手机号的

**Comment by 0xlane** [comment]
没绑定的暂时不行，找key是通过手机号定位的

**Comment by DMOMAD** [comment]
通过昵称，微信号这些定位如何

**Comment by 0xlane** [comment]
手机号的格式是固定的 都是数字，昵称、微信号没那么规矩，可以包含的字符种类太多了

**Comment by DMOMAD** [comment]
微信4.0更新的时候是不是看了你的代码然后把搜索手机类型给隐藏了

**Comment by 0xlane** [comment]
找不到手机类型字符串了，可能变成了数字表示了（0、1那种），如果有的话应该也在手机号附近，单个数字形式的对定位没啥帮助所以我也没去找，大多数正常用的基本都绑了手机号，所以直接改用手机号定位了

**Comment by 0xlane** [comment]
没绑手机号的，也不是没办法，需要搜索所有可能表示用户信息的位置，挨个找wxid和DataDir里的wxid一致的就是了，不过需要改的代码有点多，后面看情况再改吧。

**Comment by 0xlane** [comment]
或者不找手机号，直接暴力搜key也行，内存可能是key的地址数量在200-3000，有兴趣或个人有必要的话自己去掉找手机号的逻辑试一下

**Comment by 0xlane** [comment]
https://github.com/0xlane/wechat-dump-rs/issues/41

**Comment by xumingyong** [comment]
知道手机号码，但是没有登录，能否解密呢？
实际上，这种场景的用途才最广泛。肯定大神继续研发。

**Comment by 0xlane** [comment]
> 知道手机号码，但是没有登录，能否解密呢？ 实际上，这种场景的用途才最广泛。肯定大神继续研发。

解密的key是登录后才有的

**Comment by xumingyong** [comment]
也就是说，在未登录的情况下，仅靠wechat files中的文件，是无法decrypt sqlite的？

**Comment by xumingyong** [comment]
比如，我的微信曾经登录了3个号A、B、C。当我登录A时，是无法破解B的wxid的sqlite？

**Comment by 0xlane** [comment]
> 比如，我的微信曾经登录了3个号A、B、C。当我登录A时，是无法破解B的wxid的sqlite？

没办法，key是存储在云端的，登录的时候下发

**Comment by xumingyong** [comment]
我明白了，如果官方出手，查询云上的历史key，是可以破译的。是这样吧？

**Comment by 0xlane** [comment]
> 我明白了，如果官方出手，查询云上的历史key，是可以破译的。是这样吧？

他云端数据库里有，你本地的聊天也是从云端同步下来的，不用破译你本地的

**Comment by xumingyong** [comment]
但是还有疑问，每次登录时下发的key不同，不可能每次都去对sqlite重新加密一次吧。

**Comment by xumingyong** [comment]
还是说每个key对应一个手机号，key恒久不变

**Comment by 0xlane** [comment]
> 还是说每个key对应一个手机号，key恒久不变

可以理解为每个设备一个key，一般不变，清除数据重新安装或程序升级可能会变，没测试过具体什么情况下会变

**Comment by xumingyong** [comment]
还有一个小问题请指教。如果在微信中删除了聊天记录，在sqlite还有留存信息吗？

**Comment by 0xlane** [comment]
> 还有一个小问题请指教。如果在微信中删除了聊天记录，在sqlite还有留存信息吗？

没了

**Comment by xumingyong** [comment]
> 下来的，不用破译你本地的

云端也不可能永久保存啊，容量极其大。
