### ISSUE TITLE
请问怎么使用-r参数

### ISSUE THREAD

**Issue by mengzhisuoliu** [0xlane/wechat-dump-rs#33]
D:\wechat-dump-rs>wechat-dump-rs.exe -r -f C:\message_0.db
thread 'main' panicked at src/main.rs:1238:14:
param error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 0xlane** [comment]
https://github.com/0xlane/wechat-dump-rs/blob/3977c159f5c7ebb191e2b93cb4342c9affdfda6d/README.md?plain=1#L52-L62

需要和 -k 连用，key不加任何参数获取

**Comment by 0xlane** [comment]
https://github.com/0xlane/wechat-dump-rs?tab=readme-ov-file#%E4%BD%BF%E7%94%A8-sqlcipher-browser-%E6%B5%8F%E8%A7%88%E6%95%B0%E6%8D%AE%E5%BA%93

**Comment by mengzhisuoliu** [comment]
谢谢哦,刚看到原来有demo,看漏了
