### ISSUE TITLE
感谢大佬，请问下4.0还可能像3.x版本一样通过固定地址去获取key吗

### ISSUE THREAD

**Issue by SuxueCode** [0xlane/wechat-dump-rs#34]
今天搜4.0相关的时候，看到了看雪发现大佬已经解完4.0了，太狠了，向大佬学习
因为这方面不是很懂，想问一下4.x还能像3.x这类固定地址去获取key吗
然后根据大佬的算法解密了db一看，这库表两眼发黑，又得重构了.....

**Comment by 0xlane** [comment]
4.0不是静态存储了，放到了堆上，应该没办法直接按固定的偏移找，需要其他的辅助偏移定位，比如CipherConfig类的虚函数表之类的，也是需要搜索内存

**Comment by SuxueCode** [comment]
好的，感谢大佬指导，那我更新的时候有得学了
