### ISSUE TITLE
请问老师是到哪个范围搜索KEY的？

### ISSUE THREAD

**Issue by loudixiaokai** [0xlane/wechat-dump-rs#36]
老师，我以前没听过RUST语言，所以实在看不懂代码。
我想请问下搜索KEY（或KEY的地址），是从手机号位置处往前搜索吗？我看我电脑上运行wechat-dump-rs后，搜索到的KEY位置离手机号位置以经偏移了几千万个字节了，需要往前遍历这么远吗？

**Comment by 0xlane** [comment]
key在内存里的存储结构是固定的，可以看一下代码里的yara规则，先找到所以符合的地址，再挨个搜，离手机号所在内存越近越快被找到

**Comment by 0xlane** [comment]
先关闭了，可以直接tg联系我
