### ISSUE TITLE
绑定手机号的也不行

### ISSUE THREAD

**Issue by lujihong** [0xlane/wechat-dump-rs#37]
[+] wechat version is 4.0.1.11
thread 'main' panicked at src/main.rs:558:14:
unbale to find data dir
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lujihong** [comment]
thread 'main' panicked at src/main.rs:665:10:
h:\\Mac\Home\Documents\xwechat_files\wxid_xxxxx\db_storage\biz\biz.db is not exsit: Os { code: 3, kind: NotFound, message: "系统找不到指定的路径。" }

前面为啥会多出一个h: 我的是：\\Mac\Home\Documents\xwechat_files\wxid_xxxxx\db_storage\biz\biz.db 这个路径

**Comment by 0xlane** [comment]
不是windows吗，windows全路径都是盘符开头

**Comment by lujihong** [comment]
> 不是windows吗，windows全路径都是盘符开头

mac系统中的虚拟机安装的windows

**Comment by 0xlane** [comment]
这种情况可以使用-p参数+-d参数，比如 wechat_dump_rs.exe -p 1360 -d \Mac\Home\Documents\xwechat_files\wxid_xxxxx\
-p 指定微信进程 pid，-d 是数据目录

**Comment by 0xlane** [comment]
h应该是mac映射到windows里的盘符吧，windows里完整路径都是 盘符开头，你用的这个4.0.1.11版本应该可以在微信设置里看到一个完整的路径，看一下是啥

**Comment by lujihong** [comment]
> h应该是mac映射到windows里的盘符吧，windows里完整路径都是 盘符开头，你用的这个4.0.1.11版本应该可以在微信设置里看到一个完整的路径，看一下是啥

微信设置里面没有盘符的直接是：\\Mac\Home\Documents...

**Comment by 0xlane** [comment]
那按我上面方法试试能行吗

**Comment by lujihong** [comment]
> wechat_dump_rs.exe -p 1360 -d
这种方式找不到key

[+] wechat version is 4.0.1.11
[+] found pre address count: 9361
[+] searching key in pre addresses...
[!] no found key!!
=======================================
ProcessId: 10880
WechatVersion: 4.0.1.11
AccountName: xxxxxxx
NickName: xxxxxx
Phone: xxxxxxxx
DataDir: \\Mac\Home\Documents\xwechat_files\xxxxxx\
key: unknown

敏感信息我替换为xxx了

**Comment by 0xlane** [comment]
这么奇怪🤔

**Comment by lujihong** [comment]
会不会是因为升级到4.0.1.11的原因？

**Comment by 0xlane** [comment]
应该不是，我在我的环境测试了这个版本。你有正常点的环境吗，我没测过mac虚拟机里，尤其这种windows用户目录和mac目录共用的

**Comment by lujihong** [comment]
我目前没有真实的windows环境，不过我可以在微信里面修改成正常的db路径试试

**Comment by lujihong** [comment]
我修改成正常路径也不行，反而昵称和手机号都不对了。

[+] wechat version is 4.0.1.11
[+] found pre address count: 9606
[+] searching key in pre addresses...
[!] no found key!!
=======================================
ProcessId: 6488
WechatVersion: 4.0.1.11
AccountName:
NickName: 13559782626 //这个数据不对
Phone: 13559782626 //这个数据不对
DataDir: C:\Users\xxx\Documents\xwechat_files\xxxxx\
key: unknown
=======================================

**Comment by lujihong** [comment]
再次重启微信后报错：

[+] wechat version is 4.0.1.11
thread 'main' panicked at src/main.rs:537:85:
called `Result::unwrap()` on an `Err` value: invalid utf8 string
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lujihong** [comment]
又一次重启微信后运行结果昵称、手机号登都查找正确了，但是key还是提示：unknown

**Comment by 0xlane** [comment]
这个我不好排查，你有兴趣手动找key吗，需要用CE😄

**Comment by 0xlane** [comment]
我指导下你怎么找

**Comment by lujihong** [comment]
> 这个我不好排查，你有兴趣手动找key吗，需要用CE😄

我有ce，但是我不会

**Comment by 0xlane** [comment]
在这里有行，就4、5步，简单。先打开微信，如果登录了就退出登录回到确认登录界面，然后CE里通过窗口”微信-测试版“打开微信进程

**Comment by 0xlane** [comment]
然后随便搜个东西比如你的手机号，找到个内存，右键打开浏览所在内存区域

**Comment by 0xlane** [comment]
在弹出的窗口里的反汇编区域，按ctrl+G，跳转到 Weixin.dll+47C4B0 这个地址，在这个地址上右键 ”添加断点“

**Comment by 0xlane** [comment]
然后登录微信，应该会被中断到这个位置

**Comment by lujihong** [comment]
停留在登录界面搜不到手机号

**Comment by 0xlane** [comment]
那下面手动添加这个地址：Weixin.dll+47C4B0

**Comment by 0xlane** [comment]
> 停留在登录界面搜不到手机号

那下面手动添加这个地址：Weixin.dll+47C4B0

**Comment by 0xlane** [comment]
然后在加好的地址上，右键 - 反汇编此内存区域

**Comment by lujihong** [comment]
手动添加了，在反汇编内存区域怎么操作？

**Comment by 0xlane** [comment]
> 手动添加了，在反汇编内存区域怎么操作？

那个地址位置右键，添加断点

**Comment by lujihong** [comment]
添加断点了，然后点击登录后点击运行吗？

**Comment by lujihong** [comment]
那然后怎么操作？

**Comment by 0xlane** [comment]
命中断点之后，ce里能看到 rdx 寄存器的值，复制一下，在下面的数据窗口ctrl+g跳转过去，这个位置的数据截个图看看

**Comment by lujihong** [comment]
哈哈，我一截图全部变成问号了？

**Comment by 0xlane** [comment]
你不会点运行了吧

**Comment by lujihong** [comment]
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/5db9d07a-b155-402b-b238-fd632393b7b5">
没有点击运行啊

**Comment by lujihong** [comment]
不截图就正常，截图就变问号了

**Comment by 0xlane** [comment]
rdx不是这个地址呀

**Comment by lujihong** [comment]
rdx复制出来是这个：3402BFE0B0

**Comment by 0xlane** [comment]
鼠标点一下下面一堆问号这个地方，然后ctrl+g弹出个窗口写 rdx这个地址进去回车

**Comment by lujihong** [comment]
IMG_2818.HEIC

**Comment by lujihong** [comment]
你等一下，我拍照的图片太大了传不上来

**Comment by lujihong** [comment]
![IMG_2818](https://github.com/user-attachments/assets/7d0acac8-0153-4aea-8308-29ec990de191)

**Comment by lujihong** [comment]
截图就全部变成问号，这是我拍照的，你看看还需要什么

**Comment by 0xlane** [comment]
然后就结束了，跳转到 1c0ea766c60 这个地址就是你的key

**Comment by 0xlane** [comment]
一共32位，复制出来空格删了，试试用 wechat-dump-rs.exe -k xxxxxxxx -f \path\to\xxxxxxx.db --vv 4 -o xxxx.db 就能解。-k是你的key -f是你要解的db文件路径，-o 是输出路径

**Comment by lujihong** [comment]
> 然后就结束了，跳转到 1c0ea766c60 这个地址就是你的key

请问这个地址是怎么来的

**Comment by 0xlane** [comment]
上面图里位置开头8字节倒转过来就是

> > 然后就结束了，跳转到 1c0ea766c60 这个地址就是你的key
> 
> 请问这个地址是怎么来的

**Comment by 0xlane** [comment]
解成功了吗

**Comment by lujihong** [comment]
是这个吗？

00 12 68 39 BA 09 4D 14 A3 60 15 56 21 44 23 6C 00 E5 8F 83 8D 45 48 CC AB 5A 66 96 C8 8B FF A6 00 72 32 00 64 65 00

**Comment by 0xlane** [comment]
> 是这个吗？
> 
> 00 12 68 39 BA 09 4D 14 A3 60 15 56 21 44 23 6C 00 E5 8F 83 8D 45 48 CC AB 5A 66 96 C8 8B FF A6 00 72 32 00 64 65 00

不知道呀，每个用户的都不一样，是从你找到的那个地址复制出来的吗，确定是的话就是这个

**Comment by 0xlane** [comment]
> 是这个吗？
> 
> 00 12 68 39 BA 09 4D 14 A3 60 15 56 21 44 23 6C 00 E5 8F 83 8D 45 48 CC AB 5A 66 96 C8 8B FF A6 00 72 32 00 64 65 00

如果你的是这个的话，我大概就知道为啥程序无法自动找到了(no found key)。。你先确认下key是不是这个吧

**Comment by lujihong** [comment]
执行命令：.\wechat-dump-rs.exe -k 00126839BA094D14A36015562144236C00E58F838D4548CCAB5A6696C88BFFA600723200646500 -f C:\Users\xxx\Documents\xwechat_files\xxx\db_storage\biz\biz.db --vv 4 -o biz.db

结果如下：
thread 'main' panicked at src/main.rs:1231:81:
called `Result::unwrap()` on an `Err` value: Hash verification failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lujihong** [comment]
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/d73a9aa2-0b12-4b4a-84c3-ccf33c9b0c83">
是这段吗？

**Comment by 0xlane** [comment]
是在断点中断的情况下看的吧，运行微信这里会变

**Comment by lujihong** [comment]
> 是在断点中断的情况下看的吧，运行微信这里会变

是啊，是中断状态看的

**Comment by 0xlane** [comment]
那这个应该就是你的key

**Comment by 0xlane** [comment]
> 执行命令：.\wechat-dump-rs.exe -k 00126839BA094D14A36015562144236C00E58F838D4548CCAB5A6696C88BFFA600723200646500 -f C:\Users\xxx\Documents\xwechat_files\xxx\db_storage\biz\biz.db --vv 4 -o biz.db
> 
> 结果如下： thread 'main' panicked at src/main.rs:1231:81: called `Result::unwrap()` on an `Err` value: Hash verification failed note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

这个报错是key和文件不匹配，文件是其他微信用户的？

**Comment by lujihong** [comment]
是和当前登录用户是一致的

**Comment by 0xlane** [comment]
保证数据文件和微信进程是对应的，从哪个微信进程里找到的key就只能用在这个进程生成的文件里

**Comment by lujihong** [comment]
确定是正确的

**Comment by 0xlane** [comment]
换个文件试试，或者Documents\xwechat_files数据全清了重新安装微信

**Comment by 0xlane** [comment]
> 换个文件试试，或者Documents\xwechat_files数据全清了重新安装微信

数据全清了再重新安装微信的话，key可能会变，还需要再去找

**Comment by 0xlane** [comment]
看下biz.db目录里有shm和wal后缀的文件吗

**Comment by lujihong** [comment]
换个文件不行，我清除后重试吧

**Comment by lujihong** [comment]
> 看下biz.db目录里有shm和wal后缀的文件吗

有的

**Comment by 0xlane** [comment]
好吧，你这个太奇怪了

**Comment by 0xlane** [comment]
还有个确定key是不是这个的方法：重启微信，再按之前方法找一次key，如果找到的还是这一串的话，那应该就没错，如果每次重启微信都变就不是这个。

**Comment by lujihong** [comment]
第一次找的：00126839BA094D14A36015562144236C00E58F838D4548CCAB5A6696C88BFFA6007232006465
第二次找的：00126839BA094D14A36015562144236C00E58F838D4548CCAB5A6696C88BFFA600723200332E

**Comment by 0xlane** [comment]
> 第一次找的：00126839BA094D14A36015562144236C00E58F838D4548CCAB5A6696C88BFFA6007232006465 第二次找的：00126839BA094D14A36015562144236C00E58F838D4548CCAB5A6696C88BFFA600723200332E

咦，你复制多了，这都38位了

**Comment by 0xlane** [comment]
00126839BA094D14A36015562144236C00E58F838D4548CCAB5A6696C88BFFA6

**Comment by 0xlane** [comment]
这才是你的key，试试这个

**Comment by lujihong** [comment]
哈哈，是的，可以了

**Comment by 0xlane** [comment]
解开了吗

**Comment by lujihong** [comment]
是的，不知道能打开否

**Comment by 0xlane** [comment]
解开了就能打开

**Comment by lujihong** [comment]
可以打开

**Comment by 0xlane** [comment]
行，我也知道为啥我程序no found key了

**Comment by lujihong** [comment]
嗯，你修改后编译一下我测试看行不

**Comment by 0xlane** [comment]
https://github.com/0xlane/wechat-dump-rs/blob/ad98c380416451151f12317c6f51d297562677ed/src/main.rs#L691-L692

这里定的key里不能出现2个及以上00

**Comment by 0xlane** [comment]
已修改为 < 5，有很多00的情况比较少见，等后面如果再出现超出这个范围的话再改

**Comment by 0xlane** [comment]
已发布v1.0.21，等自动构建完成了可以再试试。 /Mac 路径的问题先不修复，使用-p+-d参数解决

**Comment by lujihong** [comment]
嗯嗯

**Comment by lujihong** [comment]
v1.0.21 版本还是不行
.\wechat-dump-rs.exe -p 4936 -d C:\Users\xxx\Documents\xwechat_files\xxx\

[+] wechat version is 4.0.1.11
thread 'main' panicked at src/main.rs:537:85:
called `Result::unwrap()` on an `Err` value: invalid utf8 string
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 0xlane** [comment]
看报错位置是解析账号名的时候出现了非utf8字符，再开一个issue吧，这个太长了
