### ISSUE TITLE
v1.0.21 版本在某些时候还是不行，重新启动微信又可以了。

### ISSUE THREAD

**Issue by lujihong** [0xlane/wechat-dump-rs#38]
.\wechat-dump-rs.exe -p 4936 -d C:\Users\xxx\Documents\xwechat_files\xxx\

[+] wechat version is 4.0.1.11
thread 'main' panicked at src/main.rs:537:85:
called Result::unwrap() on an Err value: invalid utf8 string
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by 0xlane** [comment]
账号名都是正常的英文数字吗

**Comment by lujihong** [comment]
比较奇怪的是我重启wei又可以了

**Comment by 0xlane** [comment]
行，那啥时候又出现这个错误了，可以用CE搜一下绑定的手机号，应该有且仅有1个地址，右键浏览这个地址附近的数据（上下10行范围，应该能看到手机号、昵称、账号名在一块，适当打一下码）到时候截个图我看看

**Comment by lujihong** [comment]
我发现了一个问题，就是运行v1.0.21版本后当报这个错误的时候：invalid utf8 string
我自己用golang实现的一个版本，仅依赖手机号搜索key，也不能搜索到正确的key。但是我重启微信后v1.0.21运行后正常可以获取到所有正确的数据。同时我的golang实现的版本也可以搜索到正确的key。不知道是什么原因。

**Comment by 0xlane** [comment]
> 行，那啥时候又出现这个错误了，可以用CE搜一下绑定的手机号，应该有且仅有1个地址，右键浏览这个地址附近的数据（上下10行范围，应该能看到手机号、昵称、账号名在一块，适当打一下码）到时候截个图我看看

得给我看这个才能知道

**Comment by lujihong** [comment]
不好复现，偶尔才出现这个情况

**Comment by lujihong** [comment]
在v1.0.21版本运行提示invalid utf8 string，我golang实现的版本也可以搜索到key了，但是我发现找到的手机号不对，内存地址和ce搜索手机号的地址也不一样：
Found phone number 15911111120 at address 0x25f80e2b108
CE搜索我绑定的手机号内存地址是：25FFA25DD58

**Comment by lujihong** [comment]
> 行，那啥时候又出现这个错误了，可以用CE搜一下绑定的手机号，应该有且仅有1个地址，右键浏览这个地址附近的数据（上下10行范围，应该能看到手机号、昵称、账号名在一块，适当打一下码）到时候截个图我看看

这个区域我没看到昵称手机号和账号名啊

**Comment by lujihong** [comment]
![image](https://github.com/user-attachments/assets/3ff80305-d474-4a74-829e-dfac05738701)

**Comment by lujihong** [comment]
你看看还需要补充截图不？

**Comment by lujihong** [comment]
![image](https://github.com/user-attachments/assets/83a11cb1-9e34-4221-9329-ecd08d5fcfe9)
图上的微信号是以前的，我修改过微信号的

**Comment by 0xlane** [comment]
话说你这个图里为啥都重叠了，没看到手机号的位置，参考 https://github.com/0xlane/wechat-dump-rs/issues/24#issuecomment-2475661350 别人截的

**Comment by 0xlane** [comment]
重叠在一起没办法看

**Comment by lujihong** [comment]
我也奇怪为啥重叠了，等下次复现的时候我再看看吧

**Comment by 0xlane** [comment]
右键 set custom alignment 改成16可能不重叠。我更新了个1.0.22版本，打印了一下找到的手机号地址，可以顺便看看地址和ce里搜到的是否一致

**Comment by lujihong** [comment]
![image](https://github.com/user-attachments/assets/2b4a3e3b-4f49-473c-b290-00212ec6750f)
<img width="764" alt="image" src="https://github.com/user-attachments/assets/c3a464fc-94ec-4b08-b669-58c153bf77dd">
这个地址的并不是我的手机号

**Comment by lujihong** [comment]
![image](https://github.com/user-attachments/assets/6656d10a-9792-43ce-a6e2-579d6f8bf001)
这个才是我的号码的位置

**Comment by 0xlane** [comment]
ok，内存里有多个手机号位置特征，找错了导致失败了

**Comment by 0xlane** [comment]
我有时间了想想怎么改进一下

**Comment by 0xlane** [comment]
调整了下寻找用户信息的规则，可以试试v1.0.23

**Comment by lujihong** [comment]
> 调整了下寻找用户信息的规则，可以试试v1.0.23

好
