### ISSUE TITLE
运行报错：thread 'main' panicked at src/main.rs:537:85：called Result::unwrap() on an Err value: invalid utf8 string

### ISSUE THREAD

**Issue by sqxiangxin** [0xlane/wechat-dump-rs#40]
版本：v1.0.21

![image](https://github.com/user-attachments/assets/daf7ba93-6f3b-4c69-b656-a3e8760280f1)

[+] wechat version is 4.0.1.11
thread 'main' panicked at src/main.rs:537:85:
called `Result::unwrap()` on an `Err` value: invalid utf8 string

**Comment by 0xlane** [comment]
这是读账号名的时候解析字符串失败了，方便参考 https://github.com/0xlane/wechat-dump-rs/issues/24#issuecomment-2475661350 用CE截个图吗，CE里搜绑定的手机号

**Comment by 0xlane** [comment]
我更新了个1.0.22版本，打印了一下找到的手机号地址，可以顺便看看地址和ce里搜到的是否一致

**Comment by 0xlane** [comment]
已知微信内存中包含多个手机号位置特征时，未能正确定位到真实手机号位置导致的 https://github.com/0xlane/wechat-dump-rs/issues/38 ，应该是偶尔出现，后面我想想怎么优化

**Comment by sqxiangxin** [comment]
![image](https://github.com/user-attachments/assets/a6da36d5-1cf7-42a0-a516-199d4020bec8)
内存里 和查询出来的手机号码是一致的 对的

**Comment by 0xlane** [comment]
上面说的是thread 'main' panicked at src/main.rs:537:85:
called Result::unwrap() on an Err value: invalid utf8 string 这个问题，偶现的

你刚发的这个图没报这个错，是找不到key，算另外一个问题。。。你有兴趣手动找一下你的key吗

**Comment by 0xlane** [comment]
手动找 key参考下 https://github.com/0xlane/wechat-dump-rs/issues/37#issuecomment-2513737851

**Comment by sqxiangxin** [comment]
参考了。还是不会操作 -。-

**Comment by 0xlane** [comment]
调整了下key地址过滤条件，可以再试试1.0.23
