### ISSUE TITLE
关于未绑定手机号

### ISSUE THREAD

**Issue by 0xlane** [0xlane/wechat-dump-rs#41]
在 no-phone 分支去掉了搜手机号的逻辑，不搜手机号也不搜昵称用户名只搜key和数据目录。

没绑手机号的可以临时用一下，下载 [no-phone](https://github.com/0xlane/wechat-dump-rs/releases?q=no-phone&expanded=true) 版本。

**Comment by lujihong** [comment]
测试了可以找到key

**Comment by xumingyong** [comment]
> 测试了可以找到key

在3.9版本下有没有no phone版本？

**Comment by 0xlane** [comment]
> > 测试了可以找到key
> 
> 在3.9版本下有没有no phone版本？

3.x本来就不找手机号

**Comment by xumingyong** [comment]
大神，能不能加个你的wx，求赐教
