### ISSUE TITLE
Cannot dump phone string on WeChat Version 3.X?

### ISSUE THREAD

**Issue by NickYan7** [0xlane/wechat-dump-rs#42]
Excellent work! I love this project, it helps me a lot.

However it seems cannot dump phone string on WeChat Version 3.X, the Version 4.X can work properly. 

While checking function `dump_wechat_info_v3`, I either not found the function that analysis phone string like code beblow in `dump_wechat_info_v4`: 
```rust
...
fn dump_wechat_info_v4(
...
    let phone_str_address = phone_str_match.base + phone_str_match.offset + 0x10;
    let phone_str = read_string(pid, phone_str_address, 11).unwrap();
...
```

Please check this, thanks.

**Comment by 0xlane** [comment]
微信3.x不需要手机号定位key所以就没去获取。微信3.x是通过手机类型定位的key，微信4.x是通过手机号定位的key，所以不管是4.x还是4.x打印的其他信息都只是用来辅助找key的。

**Comment by xumingyong** [comment]
哪个命令开关可以直接取出key
