### ISSUE TITLE
v1.0.23 找不到db路径

### ISSUE THREAD

**Issue by lujihong** [0xlane/wechat-dump-rs#46]
这里我觉得可以判断盘符后面是否是两个\\\，在windows系统中，\\\ 开头的路径通常是 UNC（Universal Naming Convention，通用命名约定）路径，用于访问网络资源，假设条件成立则移除前面的h:即可正常访问了。

h:\\\Mac\Home\Documents\xwechat_files\xxxx\db_storage\biz\biz.db is not exsit: Os { code: 3, kind: NotFound, message: "系统找不到指定的路径。" }

**Comment by lujihong** [comment]
> 我记得你之前发的路径不是一个\吗

一直是两个，github转译了，所以这次我写了三个\才显示2个的。

**Comment by 0xlane** [comment]
好吧

**Comment by 0xlane** [comment]
我说呢，当时看着奇奇怪怪的

**Comment by 0xlane** [comment]
我测试下unc

**Comment by 0xlane** [comment]
试试1.0.24呢
