### ISSUE TITLE
这个yara规则并不能匹配所有情况

### ISSUE THREAD

**Issue by lujihong** [0xlane/wechat-dump-rs#47]
rule GetUserInfoOffset
    {
        strings:
            $a = /(.{16}[\x00-\x20]\x00{7}(\x0f|\x1f)\x00{7}){2}.{16}[\x01-\x20]\x00{7}(\x0f|\x1f)\x00{7}[0-9]{11}\x00{5}\x0b\x00{7}\x0f\x00{7}.{25}\x00{7}\x2f\x00{7}/
        condition:
            $a
    }
    
   **原因如下：**
   
   一、第一个微信号（设置了微信号，绑定了手机号）
1、第一次登录结构：
77 61 6E 67 5F 78 69 61 6F 00 00 00 00 00 00 00 09 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 6D 69 6E 67 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 31 33 39 32 34 35 36 37 38 39 30 00 00 00 00 00 0B 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 65 90 01 00 01 00 00 00 F0 47 DC CD 3F 01 00 00 00 00 00 00 00 00 00 00 28 00 00 00 00 00 00 00 2F 00 00 00 00 00 00 00
2、第二次登录结构：
77 61 6E 67 5F 78 69 61 6F 00 00 00 00 00 00 00 09 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 6D 69 6E 67 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 31 33 39 32 34 35 36 37 38 39 30 00 00 00 00 00 0B 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 65 90 01 00 01 00 00 00 70 C4 05 D6 3F 01 00 00 00 00 00 00 00 00 00 00 28 00 00 00 00 00 00 00 2F 00 00 00 00 00 00 00
3、第三次登录结构：
77 61 6E 67 5F 78 69 61 6F 00 00 00 00 00 00 00 09 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 6D 69 6E 67 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 31 33 39 32 34 35 36 37 38 39 30 00 00 00 00 00 0B 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 65 90 01 00 01 00 00 00 50 1C C1 88 97 02 00 00 00 00 00 00 00 00 00 00 28 00 00 00 00 00 00 00 2F 00 00 00 00 00 00 00
备注：
77 61 6E 67 5F 78 69 61 6F 是微信号
6D 69 6E 67 是微信昵称
31 33 39 32 34 35 36 37 38 39 30 是手机号

二、第二个微信号（设置了微信号，未绑定手机号）
1、第一次登录结构：
6C 69 5F 68 75 61 5F 6D 65 69 00 00 00 00 00 00 09 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 72 6F 73 65 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 21 90 01 00 01 00 00 00 F0 F0 1B D1 3F 01 00 00 00 00 00 00 00 00 00 00 1B 00 00 00 00 00 00 00 1F 00 00 00 00 00 00 00
2、第二次登录结构：
6C 69 5F 68 75 61 5F 6D 65 69 00 00 00 00 00 00 09 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 72 6F 73 65 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 21 90 01 00 01 00 00 00 70 BE 46 CC 3F 01 00 00 00 00 00 00 00 00 00 00 1B 00 00 00 00 00 00 00 1F 00 00 00 00 00 00 00
3、第三次登录结构：
6C 69 5F 68 75 61 5F 6D 65 69 00 00 00 00 00 00 09 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 72 6F 73 65 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 21 90 01 00 01 00 00 00 80 2A E8 D3 3F 01 00 00 00 00 00 00 00 00 00 00 1B 00 00 00 00 00 00 00 1F 00 00 00 00 00 00 00
备注：
6C 69 5F 68 75 61 5F 6D 65 69 是微信号
72 6F 73 65 是微信昵称

三、第三个微信号（未设置微信号，绑定了手机号）：
1、第一次登录结构：
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 80 F9 2A 20 67 01 00 00 00 00 00 00 00 00 00 00
13 00 00 00 00 00 00 00 1F 00 00 00 00 00 00 00 31 35 38 34 35 36 37 38 39 31 32 00 00 00 00 00 0B 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 BD 90 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00
备注：
80 F9 2A 20 67 01 是指向微信昵称地址的指针
31 35 38 34 35 36 37 38 39 31 32 是手机号

四、第四个微信号（未设置微信号，绑定了手机号）：
1、第一次登录结构：
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 53 75 6E 6E 79 44 61 79 00 00 00 00 00 00 00 00
06 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 31 35 39 32 34 35 36 37 38 39 30 00 00 00 00 00 0B 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 65 90 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00
备注：
53 75 6E 6E 79 44 61 79 是微信昵称
31 35 39 32 34 35 36 37 38 39 30 是手机号

五、另外两种情况的猜测（未设置微信号，未绑定手机号）
1、第一种
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 80 F9 2A 20 67 01 00 00 00 00 00 00 00 00 00 00 13 00 00 00 00 00 00 00 1F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0B 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 BD 90 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00
2、第二种
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 53 75 6E 6E 79 44 61 79 00 00 00 00 00 00 00 00
06 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0B 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 65 90 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00
备注：
第一种中的80 F9 2A 20 67 01 是指向微信昵称地址的指针
第二种中的53 75 6E 6E 79 44 61 79 是微信昵称

**Comment by lujihong** [comment]
以上数据已做脱敏处理，并非真实的昵称、微信号、手机号

**Comment by 0xlane** [comment]
除了没绑手机号的，哪个情况不行呀

**Comment by 0xlane** [comment]
微信号还能没有吗？没有的话在xwechat_files目录里的数据文件夹名字用的哪个

**Comment by 0xlane** [comment]
没有微信号的情况最后的8位是0f不是2f了，然后会匹配不到
没有手机号的情况之前有说过需要用手机号定位用户信息，可以用no-phone分支的代码只搜key

**Comment by lujihong** [comment]
> 除了没绑手机号的，哪个情况不行呀

绑定了手机号，没有设置微信号

**Comment by 0xlane** [comment]
看起来应该加个0f的情况就行了

**Comment by lujihong** [comment]
> 微信号还能没有吗？没有的话在xwechat_files目录里的数据文件夹名字用的哪个

没有设置微信号就是微信原始id，而微信原始id在这个位置的内存结构中没有的

**Comment by 0xlane** [comment]
有呀

**Comment by lujihong** [comment]
> 有呀

我这里是没有的

**Comment by 0xlane** [comment]
你找的这些再前面就是

**Comment by 0xlane** [comment]
wxid
accountname
nickname
phone
这么排的，你发的是从accountname开始的

**Comment by 0xlane** [comment]
那应该和我说的这个不一样，你说的这个我知道是这样没有accountname就是wxid，还有1种没wxid有accountname的情况

> > 微信号还能没有吗？没有的话在xwechat_files目录里的数据文件夹名字用的哪个
> 
> 我没这种微信号测试，这种的数据目录的名字好像变成了昵称命名吧，好像再另外一个issue里处理过。

**Comment by 0xlane** [comment]
试试1025呢

**Comment by lujihong** [comment]
> 你找的这些再前面就是

未设置微信号，绑定了手机号的情况，再往前也没有wxid的

**Comment by 0xlane** [comment]
跑下1025我看看这种情况会报什么错

**Comment by lujihong** [comment]
没有编译可执行文件？

**Comment by 0xlane** [comment]
> 没有编译可执行文件？

得等github自动构建完成，待会就有了

**Comment by lujihong** [comment]
在我这里测试：
1、绑定了手机号，设置了微信号的可以。
2、未设置微信号，绑定了手机号的可以。
3、设置了微信号，没绑定手机号的不可以，我理解的这种是不是也应该可以找到微信号和昵称。

未设置微信号，未绑定手机号的没条件测试，这种是用qq号登录的。

**Comment by 0xlane** [comment]
第2个，wxid能显示吧

**Comment by lujihong** [comment]
> 第2个，wxid能显示吧

可以

**Comment by 0xlane** [comment]
没绑手机号的话要找微信号和昵称需要和找key一样暴力搜了，而且搜到了也不能保证准确性。

**Comment by 0xlane** [comment]
改动代码待会合并到no-phone分支后，就第3种就能搜到key了

**Comment by lujihong** [comment]
> 没绑手机号的话要找微信号和昵称需要和找key一样暴力搜了，而且搜到了也不能保证准确性。可以改，但是不想弄，暂时感觉没必要，所以才有了no-phone分支。

嗯，其实通过wxid查询contact表username字段也能查询到微信号和昵称，我用golang实现的不依赖手机号暴力搜索也可以900多毫秒就搜索到key。

**Comment by lujihong** [comment]
1.0.25版本绑定了手机号，设置了微信的号重新启动后找不到key了，手机号、微信号、昵称都是找到的。

**Comment by 0xlane** [comment]
> > 没绑手机号的话要找微信号和昵称需要和找key一样暴力搜了，而且搜到了也不能保证准确性。可以改，但是不想弄，暂时感觉没必要，所以才有了no-phone分支。
> 
> 嗯，其实通过wxid查询contact表username字段也能查询到微信号和昵称，我用golang实现的不依赖手机号暴力搜索也可以900多毫秒就搜索到key。

时间长短的影响因素一个是搜索的数量级，一个是机器性能，可能还有其他考虑不到的影响，假如时间长的话，不单单是时间长的问题cpu会持续100%就1个小工具代码里没控制线程数也没超时之类的。没有那么多人给测试，我也不是搞开发的，自己用的话怎么着都行，给别人用的话最好影响小点好

**Comment by 0xlane** [comment]
> 1.0.25版本绑定了手机号，设置了微信的号重新启动后找不到key了，手机号、微信号、昵称都是找到的。

实际key是啥，可能被之前说的那个一样被代码过滤掉了吧

**Comment by lujihong** [comment]
重新启动微后第一次运行DataDir不对：
=======================================
ProcessId: 10060
WechatVersion: 4.0.1.13
AccountName: xxxxx
NickName: xxxx
Phone: 18xxxxxxxxxx
DataDir: \\Mac\Home\Documents\xwechat_files\\wxid_xxxxxx_59d3\
key: unknown
=======================================

接着第二次运行对了：
=======================================
ProcessId: 10060
WechatVersion: 4.0.1.13
AccountName: xxxxxxx
NickName: xxxx
Phone: 18xxxxxxxxxx
DataDir: \\Mac\Home\Documents\xwechat_files\lxxxxxxx_a500\
key: 101b8a01991549f8a0f5931c925dffbb2a30310658874f62828e101bdada1534
=======================================

**Comment by 0xlane** [comment]
字好大

**Comment by 0xlane** [comment]
第1次这个目录是哪个微信的，为啥会有其他微信的目录。。。

**Comment by lujihong** [comment]
> 第1次这个目录是哪个微信的，为啥会有其他微信的目录。。。

另一个号的，估计是微信没有启动初始化好的原因吧
