### ISSUE TITLE
error when run with wechat 4.0.1.11

### ISSUE THREAD

**Issue by luozikuan** [0xlane/wechat-dump-rs#48]
I've set `RUST_BACKTRACE=full` environment, the output is as follow:
```
[+] wechat version is 4.0.1.11
thread 'main' panicked at src/main.rs:502:10:
unbale to find user info
stack backtrace:
   0:     0x7ff63ae05165 - <unknown>
   1:     0x7ff63ad75bca - <unknown>
   2:     0x7ff63adf76d7 - <unknown>
   3:     0x7ff63ae06605 - <unknown>
   4:     0x7ff63ae0643d - <unknown>
   5:     0x7ff63ae06b16 - <unknown>
   6:     0x7ff63ae066e9 - <unknown>
   7:     0x7ff63ae0663f - <unknown>
   8:     0x7ff63ae0662e - <unknown>
   9:     0x7ff63ae65371 - <unknown>
  10:     0x7ff63ae6582c - <unknown>
  11:     0x7ff63acfb122 - <unknown>
  12:     0x7ff63ad0635a - <unknown>
  13:     0x7ff63ad11777 - <unknown>
  14:     0x7ff63acf5b7a - <unknown>
  15:     0x7ff63ad14bb5 - <unknown>
  16:     0x7ff63ae4469c - <unknown>
  17:     0x7ffd78a5e8d7 - BaseThreadInitThunk
  18:     0x7ffd7907fbcc - RtlUserThreadStart
```

**Comment by 0xlane** [comment]
用1023之前的版本试试呢

**Comment by luozikuan** [comment]
> 用1023之前的版本试试呢

在 1.0.22 版本上测了下，1.0.22 能正常运行并抓取到结果

**Comment by 0xlane** [comment]
好，那应该是之前细化了下找用户信息的规则，然后你这个号可能没命中规则，需要用CE看看内存里手机号附近的内容，我看看为啥没命中

**Comment by 0xlane** [comment]
方法：CE里打开“微信（测试版）”窗口进程，搜索值类型选“字符串”，搜索值为你的手机号，应该只能搜到1个位置，搜到之后右键浏览该地址所在内存区域，截手机号上下差不多七八行的内容，敏感信息适当打码后发给我看看

**Comment by luozikuan** [comment]
> 方法：CE里打开“微信（测试版）”窗口进程，搜索值类型选“字符串”，搜索值为你的手机号，应该只能搜到1个位置，搜到之后右键浏览该地址所在内存区域，截手机号上下差不多七八行的内容，敏感信息适当打码后发给我看看

![image](https://github.com/user-attachments/assets/d95f5ff4-f9e6-4afc-832a-e1b5767ab73d)

**Comment by luozikuan** [comment]
> > 方法：CE里打开“微信（测试版）”窗口进程，搜索值类型选“字符串”，搜索值为你的手机号，应该只能搜到1个位置，搜到之后右键浏览该地址所在内存区域，截手机号上下差不多七八行的内容，敏感信息适当打码后发给我看看
> 
> ![image](https://private-user-images.githubusercontent.com/5371065/396397514-d95f5ff4-f9e6-4afc-832a-e1b5767ab73d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjExNTUsIm5iZiI6MTczNDQyMDg1NSwicGF0aCI6Ii81MzcxMDY1LzM5NjM5NzUxNC1kOTVmNWZmNC1mOWU2LTRhZmMtODMyYS1lMWI1NzY3YWI3M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDczNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWY2NzdjMjI2ZjViZjJlYjIxNjNhNTM3NGZjM2ZmMThiZTlhYWJiMmNiOGJlZDJlNGU4MTJjNjBjZGY1YmFkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gXVS1npeYIxWcAQixrm7JM_jyaSt2FCQAiuY2Ob_rFE)

注意：这个测试是我在更新微信为 4.0.1.17 版本之后做的

**Comment by 0xlane** [comment]
你好，我看着好像可以命中，现在还是报unbale to find user info吗

**Comment by 0xlane** [comment]
你上次是不是用的1024版本呢，1023、1024是有问题的命中不了你这种情况，在1025修复了一下

**Comment by luozikuan** [comment]
我一开始用的好像是 1024 版本，刚在 1025 和 1026 版本上都试了下，仍然报错，错误输出如下
```
[+] wechat version is 4.0.1.17
thread 'main' panicked at src/main.rs:507:10:
unbale to find user info
stack backtrace:
   0:     0x7ff6ddcd4645 - <unknown>
   1:     0x7ff6ddc459fa - <unknown>
   2:     0x7ff6ddcc6bb7 - <unknown>
   3:     0x7ff6ddcd5ae5 - <unknown>
   4:     0x7ff6ddcd591d - <unknown>
   5:     0x7ff6ddcd5ff6 - <unknown>
   6:     0x7ff6ddcd5bc9 - <unknown>
   7:     0x7ff6ddcd5b1f - <unknown>
   8:     0x7ff6ddcd5b0e - <unknown>
   9:     0x7ff6ddd348f1 - <unknown>
  10:     0x7ff6ddd34dac - <unknown>
  11:     0x7ff6ddbcb000 - <unknown>
  12:     0x7ff6ddbd61d1 - <unknown>
  13:     0x7ff6ddbe1602 - <unknown>
  14:     0x7ff6ddbc5b4f - <unknown>
  15:     0x7ff6ddbe4a45 - <unknown>
  16:     0x7ff6ddd13c1c - <unknown>
  17:     0x7ff94f93e8d7 - BaseThreadInitThunk
  18:     0x7ff95193fbcc - RtlUserThreadStart
```

**Comment by 0xlane** [comment]
好吧，奇怪

**Comment by 0xlane** [comment]
重启微信再试也没成功过，对吗

**Comment by 0xlane** [comment]
我试了下微信4017版本也没问题，然后看上面发的截图里也能匹配上，实际为啥命中不了暂时还不清楚

**Comment by luozikuan** [comment]
重启了一下微信，然后 1025 和 1026 版本都可以用了😂

**Comment by 0xlane** [comment]
哈哈，好，记得下次不能用的时候，先别重启微信，在CE里截个图给我看看，之前发的图可能真的是没问题的时候截的图。
