### ISSUE TITLE
关于msg表问题以及contact表extra_buffer等问题请教

### ISSUE THREAD

**Issue by sqxiangxin** [0xlane/wechat-dump-rs#50]
老师您好，耽误您一些宝贵时间 请教您一下

问题1：解密以后看到message_0.db 库内 有很多msg_xxxx的表。这些表后面的那一串好像跟群名 或者群ID有关联，但一直不知道在哪个表里能关联到这里的msg_xxx 后面的值，
比如 我想找一个群名叫：张三的群 这个群对应哪个msg_xxx呢？怎么关联起来

问题2：
contact.db.contact表 列:extra_buffer
contact.db.chat_room表  列:ext_buffer
message_0.db.Msg_xxxx表 列:source
三个表里的这三个列的二进制。如何解出来。 这里应该放着一些重要的信息。

打扰 谢谢您

**Comment by 0xlane** [comment]
另外一个问题我没看过，暂时没办法回答你了

**Comment by sqxiangxin** [comment]
好的 谢谢你
