### ISSUE TITLE
是否可以提供一个参数，输入 key 和 DataDir 路径的情况下。直接解密数据库文件到指定目录

### ISSUE THREAD

**Issue by sqxiangxin** [0xlane/wechat-dump-rs#51]
是否可以提供一个参数

输入 key 和 DataDir 路径的情况下。直接解密数据库文件到指定目录

谢谢你

**Comment by 0xlane** [comment]
我记得好像可以

**Comment by 0xlane** [comment]
试试 -k xxxx -d xxxx -o 输出路径

**Comment by 0xlane** [comment]
-d 参数需要和只能和 -p 连用，-f可以和-k连用指定目录就是扫描目录里所有db文件解密

**Comment by sqxiangxin** [comment]
收到，确认可行。谢谢你
