### ISSUE TITLE
小建议：解密数据大概需要5秒左右，可以加快吗？

### ISSUE THREAD

**Issue by sqxiangxin** [0xlane/wechat-dump-rs#52]
刚开始为了提升导出速度，以为是找key导致的时间较长，所以前面请教你如何在知道key和datadir的情况下 解密数据库
结果实验发现，在知道key和datadir的情况下使用
wechat_dump.exe -k xxx -f xxx  导出的时间大概在6秒左右
而使用
wechat_dump.exe -a 导出的时间大概在5秒左右 -。-
我也不知道为什么会这样。最终的想法是希望能尽量在最短的时间解密数据库。谢谢。
这只是一个小小的建议。但对我来说特别重要。谢谢你

**Comment by 0xlane** [comment]
暂时没办法加快了，已经是多线程跑了，速度和文件大小数量还有你的机器配置都有关系

**Comment by sqxiangxin** [comment]
谢谢
