### ISSUE TITLE
contact的extra_buffer 和chat_room的ext_buffer 能否解出来

### ISSUE THREAD

**Issue by sqxiangxin** [0xlane/wechat-dump-rs#53]
看了您的 chat_room_record_export_to_txt.py 非常厉害
然后我用了你代码里的 zstd_decompress 方法去解 contact表里的extra_buffer 和 chat_room表里的ext_buffer 都无法解开
能否请您写个示例 怎么解开 这两个表里的这两列二进制数据？万分感谢

**Comment by 0xlane** [comment]
这两个字段没看过，还不知道怎么解

**Comment by sqxiangxin** [comment]
嗯。麻烦您有空的时候 瞟一眼 ^_^
