### ISSUE TITLE
增加匹配后面的43 4E也就是CN标记可以在未绑定手机的情况下匹配到用户信息

### ISSUE THREAD

**Issue by lujihong** [0xlane/wechat-dump-rs#55]
rule GetUserInfoOffset
    {
        strings:
            $a = /(.{16}[\x00-\x20]\x00{7}(\x0f|\x1f)\x00{7}){2}.{16}[\x01-\x20]\x00{7}(\x0f|\x1f)\x00{7}[0-9]{11}\x00{5}\x0b\x00{7}\x0f\x00{7}.{25}\x00{7}(\x2f|\x1f|\x0f)\x00{7}([\x00-\xff]{8}[\x00-\xff]+?\x00{7}(\x0f|\x1f|\x2f)\x00{7})*?.*?43\x4E)/s
            condition:
            $a
    }

**Comment by 0xlane** [comment]
没绑手机号的就用no-phone就行了，不是所有都是CN

**Comment by lujihong** [comment]
no-phone版本的在绑定了手机号的情况下不能找到手机号和其他用户信息，也就是说你不知道用户有没有绑定手机号。
[test.exe.zip](https://github.com/user-attachments/files/18278799/test.exe.zip)
你可以试试我这个。

**Comment by 0xlane** [comment]
这个工具不是用来找用户手机号的

**Comment by lujihong** [comment]
是为了更快找到key嘛，可以不依赖手机号，而是用wxid和昵称啊，这两个是肯定有的

**Comment by 0xlane** [comment]
如果地区不是CN，不是也一样找不到吗

**Comment by 0xlane** [comment]
这个之前说过，不是不想优化，就是不想做而已，感觉没必要

**Comment by lujihong** [comment]
😄是这么个道理，这个CN是国家标记吧
