### ISSUE TITLE
程序找不到用户名 

### ISSUE THREAD

**Issue by Kilerd** [0xlane/wechat-dump-rs#8]
系统： win11
微信版本： 3.9.7.29

可以找得到登陆方式 iphone，但是在找用户名的过程中出问题了。

[src\main.rs:234] format!("{:#02x}", & phone_type_string_addr) = "0x7ffbc187c1b0"

![image](https://github.com/0xlane/wechat-dump-rs/assets/3162379/80dd5fe7-4a18-4686-b4d0-06a61480be94)

我看了一下 iphone 这个串的内存地址是正确的。

**Comment by Kilerd** [comment]
问题解决了。
1. account name 也可以只出现一次。 但是counter的判断导致 ac_addr 过前以至于找不到key的addr

**Comment by 0xlane** [comment]
可能和 #4 描述的情况差不多？你也没有wxid的原始微信号吗。
https://github.com/0xlane/wechat-dump-rs/blob/4705a1a71990f2d96c93c896070fc8dae06f2012/src/main.rs#L246C4-L274C6 这里的 account_name_addr 在只找到1个的时候存的地址有问题，后面我改一下

**Comment by Kilerd** [comment]
> 可能和 #4 描述的情况差不多？你也没有wxid的原始微信号吗。 https://github.com/0xlane/wechat-dump-rs/blob/4705a1a71990f2d96c93c896070fc8dae06f2012/src/main.rs#L246C4-L274C6 这里的 account_name_addr 在只找到1个的时候存的地址有问题，后面我改一下

老用户可能是没有的。 

这里的逻辑判断可能需要写成，每找到一个就寸一次addr，然后取最后的一个座位 ac_addr。

同时 account_name 那里关于指针和字面值的判断也有一些问题。
