### ISSUE TITLE
微信 3.9.7.29版本提示not found key

### ISSUE THREAD

**Issue by sunhanaix** [0xlane/wechat-dump-rs#9]
d:\tmp1>wechat-dump-rs.exe
[+] wechat version is 3.9.7.29
[+] login phone type is android
[+] wechat data dir is C:\Users\deans\Documents\WeChat Files\sunxxx
[+] account name is sunxxx
thread 'main' panicked at src\main.rs:352:9:
not found key
stack backtrace:
   0:     0x7ff741a5a5a3 - <unknown>
   1:     0x7ff7419db97b - <unknown>
   2:     0x7ff741a4e021 - <unknown>
   3:     0x7ff741a5caf4 - <unknown>
   4:     0x7ff741a5c7a3 - <unknown>
   5:     0x7ff741a5cfd0 - <unknown>
   6:     0x7ff741a5cc53 - <unknown>
   7:     0x7ff741a5cbd9 - <unknown>
   8:     0x7ff741a5cbc4 - <unknown>
   9:     0x7ff741aa0365 - <unknown>
  10:     0x7ff741978020 - <unknown>
  11:     0x7ff7419814fb - <unknown>
  12:     0x7ff741972411 - <unknown>
  13:     0x7ff741982f25 - <unknown>
  14:     0x7ff741a9f11c - <unknown>
  15:     0x7fffb50f7344 - BaseThreadInitThunk
  16:     0x7fffb54026b1 - RtlUserThreadStart

**Comment by 0xlane** [comment]
你的看起来也是没有 wxid_ 前缀微信号（#4），我没有这种号没办法测试

**Comment by sunhanaix** [comment]
发现问题，不是在这个找key的过程：我即使从mem_base开始，+1个字节，1个字节去找，也还是提示找不到key。
后面发现是原先代码里面，获得到的微信目录信息不对。
源代码：
let db_file_path = data_dir.clone() + "\\Msg\\Misc.db";这个db_file_path 获得的是 C:\Users\deans\Documents\WeChat Files\sunxxx\Msg\Misc.db；
我如果直接给它赋值我的微信实际目录：
let db_file_path="d:\\wechat2\\WeChat Files\\wxid_cpyn7pe119xxx\\Msg\\Misc.db";
那么跑起来就没问题了，可以算出正确的key

**Comment by 0xlane** [comment]
好吧，我现在代码里直接写死的默认微信数据目录，如果是改过数据目录就不行了

**Comment by 0xlane** [comment]
数据目录位置可能不是很好能自动能确定下来，稍微麻烦点，我先加个参数可以手动指定微信数据目录吧

**Comment by sunhanaix** [comment]
因为写死的微信目录不在，我就建了对应的目录，并做了相关链接指向到实际微信数据目录，程序应该也是正常识别了misc.db文件，否则会报错的。但为何读写数据验证密钥错误这块儿，就没往下跟踪了。

**Comment by 0xlane** [comment]
我昨天改了一版，用最新的release看看可以了吗

**Comment by sunhanaix** [comment]
用最新的release可以准确获得微信数据目录，可以准确获得key，没有问题 ！

**Comment by sunhanaix** [comment]
在微信3.9.7.28的x86版本中，找到的key_point_addr距离account_name_addr 差36字节，距离phone_type_string_addr 差116字节。
都不是16的整数倍，因此不是16字节对齐的。
所以程序跑失败：
C:\Users\Win10\Desktop\pc_wechat>wechat-dump-rs.exe
[+] wechat version is 3.9.7.28
[+] login phone type is android
[+] wechat data dir is C:\Users\Win10\Documents\WeChat Files\wxid_cpyn7pe119rxxx
[+] account name is sunxxx
thread 'main' panicked at src\main.rs:357:9:
not found key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

如果把key_point_addr -= 16; 改成key_point_addr -= 1;
就OK了，耗时也几乎忽略不计。
